// <auto-generated />
using finlab.Repositorio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace finlab.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20171110232837_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("finlab.Dominio.Despesas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("data");

                    b.Property<string>("grupo");

                    b.Property<string>("local");

                    b.Property<decimal>("numDoc");

                    b.HasKey("id");

                    b.ToTable("Gasto");
                });
#pragma warning restore 612, 618
        }
    }
}
